services:  
  mariadb:
    build: './mariadb'
    container_name: mariadb
    init: true
    ports:
      - '3306:3306'
    volumes:
       - 'mariadb:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    restart: always

volumes:
  mariadb:
