- hosts: "Name_serverNode"
  gather_facts: false
  become: true
  roles:
    - role: setting_docker
  tasks:
    - name: copy_requirements
      copy:
        src: "./_requirements/"
        dest: "/home/{{ ansible_user }}/app/"
        mode: '0755'
        directory_mode: '0755'

    - name: Split array values from DB_PRIVATE_IP
      set_fact:
        target: "{{ lookup('env', 'DB_PRIVATE_IP') | split(' ') }}"

    - name: execute docker compose
      shell:
        cmd: docker-compose up -d
        chdir: "/home/{{ ansible_user }}/app/"
      environment:
        DOMAIN_NAME: "{{ ansible_host }}"
        MYSQL_USER: "{{ lookup('env', 'MYSQL_USER') }}"
        MYSQL_PASSWORD: "{{ lookup('env', 'MYSQL_PASSWORD') }}"
        MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
        DATABASE_NAME: "{{ lookup('env', 'DATABASE_NAME') }}"
        SITE_TITLE: "{{ lookup('env', 'SITE_TITLE') }}"
        ADMIN_NAME: "{{ lookup('env', 'ADMIN_NAME') }}"
        ADMIN_PASSWORD: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
        ADMIN_EMAIL: "{{ lookup('env', 'ADMIN_EMAIL') }}"
        USER_NAME: "{{ lookup('env', 'USER_NAME') }}"
        USER_PASSWORD: "{{ lookup('env', 'USER_PASSWORD') }}"
        USER_EMAIL: "{{ lookup('env', 'USER_EMAIL') }}"
        DB_PRIVATE_IP: "{{ target[ansible_play_hosts.index(inventory_hostname)] }}"

    - name: all done message
      debug:
        msg: "https://{{ ansible_host }}"
